### ISSUE TITLE
Maybe a bug on version 0.6.0

### ISSUE THREAD

**Issue by nemesis-lab** [liguowang/CrossMap#38]
**Hello,
Last week I was using version 0.5.3 on COLAB and was fine.
I tried today the same code with the same data, but got this error:**

2021-11-23 04:48:11 [INFO]  Read the chain file "/content/hg38ToHg19.over.chain" 
2021-11-23 04:48:13 [INFO]  Keep variants [reference_allele == alternative_allele] ...
2021-11-23 04:48:13 [INFO]  Updating contig field ... 
Traceback (most recent call last):
  File "/usr/local/bin/CrossMap.py", line 319, in <module>
    crossmap_vcf_file(mapping = mapTree, infile= in_file, outfile = out_file, liftoverfile = chain_file, refgenome = genome_file, noCompAllele = args.no_comp_alleles, compress = args.compression, cstyle = args.cstyle)
  File "/usr/local/lib/python3.7/site-packages/cmmodule/mapvcf.py", line 115, in crossmap_vcf_file
    print("##contig=<ID=%s,length=%d,assembly=%s>" % (update_chromID(chr_template, chr_id, cstyle), target_gsize[chr_id], os.path.basename(refgenome)), file=FILE_OUT)
UnboundLocalError: local variable 'chr_template' referenced before assignment

**My input was:**

!CrossMap.py  vcf  /content/hg38ToHg19.over.chain  /content/fake65.vcf  /content/hg19.fa  out.fake.hg19.vcf --no-comp-alleles

Thanks for the help!

**Comment by liguowang** [comment]
It runs OK with my small testing vcf file. Could you please provide a sample of your input vcf file?

**Comment by nemesis-lab** [comment]
**Yes, below are some lines of my vcf**

#CHROM	POS	ID	REF	ALT	QUAL	FILTER	INFO	FORMAT	SAMPLES
chr17	41276045	.	CT	-	.	.	ba1=2;bp1=3;bp2=3;bp3=3;bp4=3;bp5=3;bp6=2;bp7=2;bs1=2;bs2=3;bs3=3;bs4=3;pm1=3;pm2=1;pm3=3;pm4=3;pm5=3;pm6=3;pp1=3;pp2=3;pp3=3;pp4=3;pp5=1;ps1=3;ps2=3;ps3=3;ps4=3;pvs1=1	.	.
chr13	32911888	.	A	G	.	.	ba1=1;bp1=3;bp2=3;bp3=2;bp4=3;bp5=3;bp6=2;bp7=1;bs1=3;bs2=3;bs3=3;bs4=3;pm1=3;pm2=2;pm3=3;pm4=3;pm5=3;pm6=3;pp1=3;pp2=3;pp3=3;pp4=3;pp5=2;ps1=3;ps2=3;ps3=3;ps4=3;pvs1=2	.	.
chr17	41246411	.	A	C	.	.	ba1=2;bp1=3;bp2=3;bp3=2;bp4=3;bp5=3;bp6=1;bp7=2;bs1=1;bs2=3;bs3=3;bs4=3;pm1=2;pm2=2;pm3=3;pm4=3;pm5=3;pm6=3;pp1=3;pp2=3;pp3=2;pp4=3;pp5=2;ps1=3;ps2=3;ps3=3;ps4=3;pvs1=2	.	.
chr13	32889792	.	A	G	.	.	ba1=1;bp1=3;bp2=3;bp3=2;bp4=1;bp5=3;bp6=1;bp7=2;bs1=2;bs2=3;bs3=3;bs4=3;pm1=3;pm2=2;pm3=3;pm4=3;pm5=3;pm6=3;pp1=3;pp2=3;pp3=3;pp4=3;pp5=2;ps1=3;ps2=3;ps3=3;ps4=3;pvs1=2	.	.
chr13	32919637	.	T	G	.	.	ba1=1;bp1=3;bp2=3;bp3=2;bp4=1;bp5=3;bp6=1;bp7=2;bs1=2;bs2=3;bs3=3;bs4=3;pm1=3;pm2=2;pm3=3;pm4=3;pm5=3;pm6=3;pp1=3;pp2=3;pp3=3;pp4=3;pp5=2;ps1=3;ps2=3;ps3=3;ps4=3;pvs1=2	.	.
chr17	41196408	.	G	A	.	.	ba1=1;bp1=3;bp2=3;bp3=2;bp4=1;bp5=3;bp6=2;bp7=2;bs1=3;bs2=3;bs3=3;bs4=3;pm1=3;pm2=2;pm3=3;pm4=3;pm5=3;pm6=3;pp1=3;pp2=3;pp3=3;pp4=3;pp5=2;ps1=3;ps2=3;ps3=3;ps4=3;pvs1=2	.	.
chr17	41197274	.	C	A	.	.	ba1=1;bp1=3;bp2=3;bp3=2;bp4=1;bp5=3;bp6=2;bp7=2;bs1=3;bs2=3;bs3=3;bs4=3;pm1=3;pm2=2;pm3=3;pm4=3;pm5=3;pm6=3;pp1=3;pp2=3;pp3=3;pp4=3;pp5=2;ps1=3;ps2=3;ps3=3;ps4=3;pvs1=2	.	.
chr17	41215825	.	C	T	.	.	ba1=1;bp1=3;bp2=3;bp3=2;bp4=1;bp5=3;bp6=2;bp7=2;bs1=2;bs2=3;bs3=3;bs4=3;pm1=3;pm2=2;pm3=3;pm4=3;pm5=3;pm6=3;pp1=3;pp2=3;pp3=3;pp4=3;pp5=2;ps1=3;ps2=3;ps3=3;ps4=3;pvs1=2	.	.
chr18	29172937	.	G	A	.	.	ba1=2;bp1=3;bp2=3;bp3=2;bp4=3;bp5=3;bp6=2;bp7=2;bs1=2;bs2=3;bs3=3;bs4=3;pm1=1;pm2=2;pm3=3;pm4=3;pm5=3;pm6=3;pp1=3;pp2=3;pp3=2;pp4=3;pp5=2;ps1=3;ps2=3;ps3=1;ps4=1;pvs1=2	.	.

**When I use version 0.5.4 runs fine:**

2021-11-23 06:22:38 [INFO]  Read the chain file "/content/hg38ToHg19.over.chain" 
2021-11-23 06:22:39 [INFO]  Keep variants [reference_allele == alternative_allele] ...
2021-11-23 06:22:39 [INFO]  Creating index for: /content/hg19.fa
2021-11-23 06:22:53 [INFO]  Updating contig field ... 
2021-11-23 06:22:53 [INFO]  Lifting over ... 
2021-11-23 06:22:53 [INFO]  Total entries: 7291
2021-11-23 06:22:53 [INFO]  Failed to map: 73

**But I got the error reported using version 0.6.0**

**Comment by liguowang** [comment]
Still could not reproduce the error. Maybe your VCF file missed the
"##contig" rows? please check.

**Comment by mofisl** [comment]
@nemesis-lab Whether you solve the ##contig problem?
 have made the same mistake, do not know how to solve
