### ISSUE TITLE
UnboundLocalError: local variable 'chr_template' referenced before assignment

### ISSUE THREAD

**Issue by WZo0o** [liguowang/CrossMap#42]
Hello, when I run CrossMap  0.6.1 with command "CrossMap.py hg19ToHg38.over.chain 2419_1KG_samples.vcf hg38.fa out.vcf", I always meet an  UnboundLocalError.

''''
(base) [wangzh@mu01 1000G]$ CrossMap.py vcf /lustre/wangzh/tools/LiftOver/hg19ToHg38.over.chain "/lustre/wangzh/mtDNA/1000G/2419_1KG_samples.vcf" "/lustre/wangzh/tools/UCSC/hg38.fa" /lustre/wangzh/mtDNA/1000G/out.vcf
2021-12-19 08:19:15 [INFO]  Read the chain file "/lustre/wangzh/tools/LiftOver/hg19ToHg38.over.chain"
2021-12-19 08:19:16 [INFO]  Filter out variants [reference_allele == alternative_allele] ...
2021-12-19 08:19:24 [INFO]  Updating contig field ...
Traceback (most recent call last):
  File "/home/wangzh/miniconda3/bin/CrossMap.py", line 319, in <module>
    crossmap_vcf_file(mapping = mapTree, infile= in_file, outfile = out_file, liftoverfile = chain_file, refgenome = genome_file, noCompAllele = args.no_comp_alleles, compress = args.compression, cstyle = args.cstyle)
  File "/home/wangzh/miniconda3/lib/python3.9/site-packages/cmmodule/mapvcf.py", line 115, in crossmap_vcf_file
    print("##contig=<ID=%s,length=%d,assembly=%s>" % (update_chromID(chr_template, chr_id, cstyle), target_gsize[chr_id], os.path.basename(refgenome)), file=FILE_OUT)
UnboundLocalError: local variable 'chr_template' referenced before assignment
'''''''
Could you help me to fix this error?

**Comment by liguowang** [comment]
Hi,
This is probably because your VCF file does not have header section. Specifically, your VCF file does not have rows starting with "##contig=" (CrossMap checks those rows to determine the style of the chromosome IDs)
