### ISSUE TITLE
Error: KeyError: '>', version=0.6.1,I want to know it

### ISSUE THREAD

**Issue by mofisl** [liguowang/CrossMap#45]
2022-02-19 02:48:44 [INFO]  Read the chain file "/liulab/luozhiheng/lddnew/out/B73_RefGen_v4_to_Zm-B73-REFERENCE-NAM-5.0.chain" 
2022-02-19 02:48:44 [INFO]  Filter out variants [reference_allele == alternative_allele] ...
2022-02-19 02:48:45 [INFO]  Updating contig field ... 
2022-02-19 02:48:45 [INFO]  Lifting over ... 
Traceback (most recent call last):
  File "/home/luozhiheng/miniconda3/bin/CrossMap.py", line 319, in <module>
    crossmap_vcf_file(mapping = mapTree, infile= in_file, outfile = out_file, liftoverfile = chain_file, refgenome = genome_file, noCompAllele = args.no_comp_alleles, compress = args.compression, cstyle = args.cstyle)
  File "/home/luozhiheng/miniconda3/lib/python3.7/site-packages/cmmodule/mapvcf.py", line 165, in crossmap_vcf_file
    fields[4] = revcomp_DNA(fields[4], True)
  File "/home/luozhiheng/miniconda3/lib/python3.7/site-packages/cmmodule/utils.py", line 94, in revcomp_DNA
    return ''.join([complement[base] for base in reversed(seq)])
  File "/home/luozhiheng/miniconda3/lib/python3.7/site-packages/cmmodule/utils.py", line 94, in <listcomp>
    return ''.join([complement[base] for base in reversed(seq)])
KeyError: '>'
Thank you

**Comment by liguowang** [comment]
I guess there are some non-standard characters int the 5th field  (i.e., the alternative allele filed) of your VCF file. Please check.
 
BTW: You can have these characters in the 5th field: 'A','C','G','T','Y','R','S','W','K','M','B','V','D','H','N','.','*'
 
Thanks
