### ISSUE TITLE
Convert VCF format files, KeyError: '>'  in CrossMap 0.6.4 

### ISSUE THREAD

**Issue by rmozafari** [liguowang/CrossMap#50]
Hi. I am getting the following KeyError message:

```
2022-09-20 05:31:41 [INFO]  Read the chain file "hg19ToHg38.over.chain.gz"                                                                        
2022-09-20 05:31:41 [INFO]  Filter out variants [reference_allele == alternative_allele] ...                                                                                                               
2022-09-20 05:31:42 [INFO]  Updating contig field ...                                                                                                                                                      
2022-09-20 05:31:42 [INFO]  Lifting over ...                                                                                                                                                               
Traceback (most recent call last):                                                                                                                                                                         
  File "/home/miniconda3/envs/snakemake/bin/CrossMap.py", line 319, in <module>                                                                                                                   
    crossmap_vcf_file(mapping = mapTree, infile= in_file, outfile = out_file, liftoverfile = chain_file, refgenome = genome_file, noCompAllele = args.no_comp_alleles, compress = args.compression, cstyle 
= args.cstyle)                                                                                                                                                                                             
  File "/home/miniconda3/envs/snakemake/lib/python3.10/site-packages/cmmodule/mapvcf.py", line 181, in crossmap_vcf_file                                                                          
    fields[4] = revcomp_DNA(fields[4], True)                                                                                                                                                               
  File "/home/miniconda3/envs/snakemake/lib/python3.10/site-packages/cmmodule/utils.py", line 94, in revcomp_DNA                                                                                  
    return ''.join([complement[base] for base in reversed(seq)])                                                                                                                                           
  File "/home/miniconda3/envs/snakemake/lib/python3.10/site-packages/cmmodule/utils.py", line 94, in <listcomp>                                                                                   
    return ''.join([complement[base] for base in reversed(seq)])                                                                                                                                           
KeyError: '>'        
```
I am converting VCF files from hg19 to hg38. The input files are:
- USCS chain file: hg19ToHg38.over.chain.gz
- USCS FASTA files by chromosomes: chr*.fa.gz (bgzip file)**
- VCF file by chromosomes: chr*.vcf.gz (bgzip file)***

**In case of the refgenome.fa files, I have tried both zipped file and unzipped file with no change in result. 
***The style of chromosome IDs is long style: "chr1"

This issue happens only for the one chromosome (# 9) and it worked great on the rest. Even for the chromosome number 9, I get the output files (vcf.gz and vcf.gz.unmap) but with the error message. Since it is a KeyError message, you can't ignore it.  

Thanks for the help!

**Comment by liguowang** [comment]
Hi,
Please check the "REF" and "ALT" fields,  if you find the ">" character, please remove them. Please let me know if this works. 

Liguo

**Comment by rmozafari** [comment]
Hi, 
Actually there are few occurrences of the "<DEL>" character were found in the "ALT" field. But this was true for all chromosomes while the error message showed up for the only one. How can I be sure that the results are reliable?

Thanks,
Reza

**Comment by liguowang** [comment]
This is the not the standard way to represent deletions (please refer to the VCF file specifications). When these variants are located on the "+" strand, CrossMap will not do anything to the "ALT" alleles. However, when these are on the "-" strand, CrossMap will try to reverse complement  the "ALT" alleles, this is why you saw the "key error". 

Liguo

**Comment by rmozafari** [comment]
Ok, thank you for your time. 

Reza
