### ISSUE TITLE
Crossmap throws error while lifting over from MAF file

### ISSUE THREAD

**Issue by Subhi** [liguowang/CrossMap#51]
Traceback (most recent call last):
  File "/Users/opt/anaconda3/bin/CrossMap.py", line 338, in <module>
    crossmap_maf_file(mapping = mapTree, infile= in_file, outfile = out_file, liftoverfile = chain_file, refgenome = genome_file, ref_name = build_name, cstyle = args.cstyle)
  File "/Users/opt/anaconda3/lib/python3.9/site-packages/cmmodule/mapmaf.py", line 84, in crossmap_maf_file
    start = int(fields[5])-1	 # 0 based
ValueError: invalid literal for int() with base 10: '1.86e+08'

**Comment by liguowang** [comment]
please don't use scientific notation (e.g., 1.86e+08) to represent genomic coordinates. This could be done silently by Excel.
