### ISSUE TITLE
Error Running CrossMap in Mac Terminal for VCF

### ISSUE THREAD

**Issue by o0stsou0o** [liguowang/CrossMap#55]
Hi guys,

I am trying to run CrossMap on terminal in Mac OS Version 11.2.3 but I'm getting an error trying to generate the vcf.  

It involves  numpy.  The version of numpy I installed is 1.24.1.  Is there a specific version of numpy I need to install?  Or perhaps do I need to install something beforehand?  I tried installing pybigwig as well.  Would any of you know what may be going wrong?  Thanks

init_gelsd failed init
Traceback (most recent call last):
  File "/Library/Python/3.8/site-packages/numpy/__init__.py", line 352, in <module>
    raise RuntimeError(msg)
RuntimeError: Polyfit sanity test emitted a warning, most likely due to using a buggy Accelerate backend.
If you compiled yourself, more information is available at:
https://numpy.org/doc/stable/user/building.html#accelerated-blas-lapack-libraries
Otherwise report this to the vendor that provided NumPy.
RankWarning: Polyfit may be poorly conditioned

Traceback (most recent call last):
  File "/usr/local/bin/CrossMap.py", line 13, in <module>
    import pyBigWig
ImportError: numpy.core.multiarray failed to import

**Comment by liguowang** [comment]
CrossMap does not a specific version of numpy. 
I just tried, I can install the laster version (1.24) without any problems. MaxOS 12.5.1

pip3 install numpy==1.24
Collecting numpy==1.24
  Downloading numpy-1.24.0-cp38-cp38-macosx_10_9_x86_64.whl (19.8 MB)
     |████████████████████████████████| 19.8 MB 2.8 MB/s
Installing collected packages: numpy
  Attempting uninstall: numpy
    Found existing installation: numpy 1.23.4
    Uninstalling numpy-1.23.4:
      Successfully uninstalled numpy-1.23.4
Successfully installed numpy-1.24.0

**Comment by o0stsou0o** [comment]
Thank you so much Dr. Wang.  Indeed.  When I installed numpy 1.24, it did
work and I got new .vcf files.

Previously there were the same errors with pip3 install numpy, pip3 install
numpy= 1.19 and pip3 install numpy=1.20.  There oddly was a different error
with pip3 install numpy=1.18.  And a harsher error with pip3 install
numpy=1.17.

At some point, I will have to learn more about the different LaPack and
OpenBlas, etc. type of underpinnings I was reading about trying to debug.
In the meantime, thank you.
