### ISSUE TITLE
CrossMap v0.6.5 KeyError: "-"

### ISSUE THREAD

**Issue by boseb** [liguowang/CrossMap#62]
Hi,
I am having KeyError:"-" while converting from hg18 to hg18 for chromosome 7 vcf file with CrossMap v0.6.5.

[bbj5535@quser34 ~]$ CrossMap.py  vcf projects/b1137/BBose/Panscan_ResultDir/hg18ToHg19.over.chain.gz  projects/b1137/BBose/Panscan_ResultDir/ResultDir_DG_98846_1_HOE_c1_panscan_v5/PreimputeQC_chr7.vcf.gz projects/b1137/BBose/Panscan_ResultDir/hg19.fa.gz projects/b1137/BBose/Panscan_ResultDir/ResultDir_DG_98846_1_HOE_c1_panscan_v5/PreimputeQC_chr7_hg19.vcf.gz
2023-09-27 07:18:16 [INFO]  Read the chain file "projects/b1137/BBose/Panscan_ResultDir/hg18ToHg19.over.chain.gz"
2023-09-27 07:18:16 [INFO]  Filter out variants [reference_allele == alternative_allele] ...
2023-09-27 07:18:16 [INFO]  Updating contig field ...
2023-09-27 07:18:16 [INFO]  Lifting over ...
Traceback (most recent call last):
  File "/home/bbj5535/.local/bin/CrossMap.py", line 319, in <module>
    crossmap_vcf_file(mapping = mapTree, infile= in_file, outfile = out_file, liftoverfile = chain_file, refgenome = genome_file, noCompAllele = args.no_comp_alleles, compress = args.compression, cstyle = args.cstyle)
  File "/home/bbj5535/.local/lib/python3.6/site-packages/cmmodule/mapvcf.py", line 183, in crossmap_vcf_file
    fields[4] = revcomp_DNA(fields[4], True)
  File "/home/bbj5535/.local/lib/python3.6/site-packages/cmmodule/utils.py", line 104, in revcomp_DNA
    return ''.join([complement[base] for base in reversed(seq)])
  File "/home/bbj5535/.local/lib/python3.6/site-packages/cmmodule/utils.py", line 104, in <listcomp>
    return ''.join([complement[base] for base in reversed(seq)])
KeyError: '-'

Please help!

Thanks,
Bose

**Comment by liguowang** [comment]
Please check if there is a dash ("-") in the alternative non-reference allele field of your VCF file (to indicate deletion? or missing?). Although this is easy to fix, VCF generally does not use "-" to indicate deletions.

**Comment by boseb** [comment]
Removed the "-" and it worked. Thanks.
