### ISSUE TITLE
Critical error with v0.3.8

### ISSUE THREAD

**Issue by mevers** [liguowang/CrossMap#7]
`CrossMap` version 0.3.8 installed with

```python
pip install CrossMap
```

using Python 3.5.2 throws the critical error

```
Traceback (most recent call last):
  File "CrossMap.py", line 27, in <module>
    from cmmodule  import bgrMerge
  File "/Users/maurits/miniconda3/lib/python3.5/site-packages/cmmodule/bgrMerge.py", line 14, in <module>
    from cmmodule  import wig_reader
  File "/Users/maurits/miniconda3/lib/python3.5/site-packages/cmmodule/wig_reader.py", line 10, in <module>
    from bx.bbi.bigwig_file import BigWigFile
  File "lib/bx/bbi/bigwig_file.pyx", line 1, in init bx.bbi.bigwig_file
  File "__init__.pxd", line 918, in init bx.bbi.bbi_file
ValueError: numpy.ufunc size changed, may indicate binary incompatibility. Expected 216 from C header, got 192 from PyObject
```

**Comment by liguowang** [comment]
Hi,
I have no idea about this error message. It relates to the bx-python package (https://github.com/bxlab/bx-python). FYI, I used bx-python (v0.8.0) without any problems.

**Comment by mt1022** [comment]
Seems to be an issue of numpy 1.15. I came across the same error, which disappeared when the numpy was updated to 1.19.
