### ISSUE TITLE
Got problem when trying to liftover bam file

### ISSUE THREAD

**Issue by songtaogui** [liguowang/CrossMap#9]
Hi,

I would like to liftover some bam files. But I got some errors when testing:

```shell
# input cmd
CrossMap.py bam test.chain test.bam
# logs and errors
Insert size = 200.000000
Insert size stdev = 30.000000
Number of stdev from the mean = 3.000000
Add tags to each alignment = False
@ 2019-12-02 18:13:05: Read chain_file:  test.chain
Traceback (most recent call last):
  File "/public/home/stgui/.linuxbrew/bin/CrossMap.py", line 1746, in <module>
    crossmap_bam_file(mapping = mapTree, chainfile = chain_file, infile = in_file, outfile_prefix = out_file, chrom_size = targetChnsert_size_stdev, fold=options.insert_size_fold,addtag=False)
  File "/public/home/stgui/.linuxbrew/bin/CrossMap.py", line 827, in crossmap_bam_file
    (new_header, name_to_id) = sam_header.bam_header_generator(orig_header = sam_ori_header, chrom_size = chrom_size, prog_name="Cre = 'coordinate',co=comments)
  File "/public/home/stgui/.linuxbrew/Cellar/python@2/2.7.16/lib/python2.7/site-packages/cmmodule/sam_header.py", line 27, in bam_h
    bamHeaderLine['HD'] = {'VN':format_ver,'SO':sort_type}
  File "pysam/libcalignmentfile.pyx", line 539, in pysam.libcalignmentfile.AlignmentHeader.__setitem__
TypeError: AlignmentHeader does not support item assignment (use header.to_dict()
```
I cannot  figure it out that what caused the error, since my test.chain file didn't change any coordinates.

And please find attached the test files:
[test.zip](https://github.com/liguowang/CrossMap/files/3910682/test.zip)

Would you have any idea of the possible reason?

Any suggestion would be grateful.

Best wishes,

SongtaoGui

**Comment by liguowang** [comment]
Hi, Songtao,

Here is what I got using the "test.bam" and "test.chain" files you provided. (I used CrossMap version 0.3.9) 

$ CrossMap.py bam  test.chain test.bam output

Insert size = 200.000000
Insert size stdev = 30.000000
Number of stdev from the mean = 3.000000
Add tags to each alignment = False
@ 2019-12-02 09:23:48: Read the chain file:  test.chain
@ 2019-12-02 09:23:48: Liftover BAM file: test.bam ==> output.bam
@ 2019-12-02 09:23:48: Done!
@ 2019-12-02 09:23:48: Sort "output.bam" and save as "output.sorted.bam"
@ 2019-12-02 09:23:48: Index "output.sorted.bam" ...
Total alignments:731
	 QC failed: 0
	 Paired-end reads:
	R1 unique, R2 unique (UU): 695
	R1 unique, R2 unmapp (UN): 18
	R1 unique, R2 multiple (UM): 0
	R1 multiple, R2 multiple (MM): 0
	R1 multiple, R2 unique (MU): 0
	R1 multiple, R2 unmapped (MN): 0
	R1 unmap, R2 unmap (NN): 0
	R1 unmap, R2 unique (NU): 18
	R1 unmap, R2 multiple (NM): 0

Output file was attached:
[output.zip](https://github.com/liguowang/CrossMap/files/3911946/output.zip)

**Comment by songtaogui** [comment]
@liguowang 
Thank you for the kind help, I have updated my CrossMap version, and yes, it works fine now.

However, I still have some questions:
1. How did CrossMap deal with the mate information (column-7 in the bam)? I have noticed that quite a proportion of the mate information were masked ( changed into "=" ) in the output.
2. How did CrossMap deal with bam headers? I have noticed that the contig info of the liftover bam file ("@SQ") were not changed accordingly, is it normal?

Thank you again for your kind help.

Best wishes,

SongtaoGui

**Comment by liguowang** [comment]
1. CrossMap will update the mate position (i.e. the "next_reference_start" ) at the same time.
2. CorssMap will update the BAM header to the target genome assembly, and the  "@SQ" fields should be updated. 

Version 0.4.0 will be released, several bugs in BAM liftover function were fixed.
